# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_pb2 as user__pb2


class UsersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBorrowedBooks = channel.unary_unary(
                '/users.Users/GetBorrowedBooks',
                request_serializer=user__pb2.UID.SerializeToString,
                response_deserializer=user__pb2.AllBooksMessage.FromString,
                )
        self.GetWaitlist = channel.unary_unary(
                '/users.Users/GetWaitlist',
                request_serializer=user__pb2.UID.SerializeToString,
                response_deserializer=user__pb2.FilteredBooksMessage.FromString,
                )
        self.AppendToWaitlist = channel.unary_unary(
                '/users.Users/AppendToWaitlist',
                request_serializer=user__pb2.UID_ISBN.SerializeToString,
                response_deserializer=user__pb2.SimpleMessage.FromString,
                )
        self.DeleteFromWaitlist = channel.unary_unary(
                '/users.Users/DeleteFromWaitlist',
                request_serializer=user__pb2.UID_ISBN.SerializeToString,
                response_deserializer=user__pb2.SimpleMessage.FromString,
                )
        self.GetRecommendations = channel.unary_unary(
                '/users.Users/GetRecommendations',
                request_serializer=user__pb2.UID.SerializeToString,
                response_deserializer=user__pb2.FilteredBooksMessage.FromString,
                )
        self.GetAllUsersInfo = channel.unary_unary(
                '/users.Users/GetAllUsersInfo',
                request_serializer=user__pb2.EmptyInfo.SerializeToString,
                response_deserializer=user__pb2.AllUsersInfoMessage.FromString,
                )
        self.GetUserInfo = channel.unary_unary(
                '/users.Users/GetUserInfo',
                request_serializer=user__pb2.UID.SerializeToString,
                response_deserializer=user__pb2.UserInfoMessage.FromString,
                )
        self.UpdateUserInfo = channel.unary_unary(
                '/users.Users/UpdateUserInfo',
                request_serializer=user__pb2.UpdateUserInfoRequest.SerializeToString,
                response_deserializer=user__pb2.SimpleMessage.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/users.Users/DeleteUser',
                request_serializer=user__pb2.UID.SerializeToString,
                response_deserializer=user__pb2.SimpleMessage.FromString,
                )


class UsersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBorrowedBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendToWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFromWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsersInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowedBooks,
                    request_deserializer=user__pb2.UID.FromString,
                    response_serializer=user__pb2.AllBooksMessage.SerializeToString,
            ),
            'GetWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaitlist,
                    request_deserializer=user__pb2.UID.FromString,
                    response_serializer=user__pb2.FilteredBooksMessage.SerializeToString,
            ),
            'AppendToWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendToWaitlist,
                    request_deserializer=user__pb2.UID_ISBN.FromString,
                    response_serializer=user__pb2.SimpleMessage.SerializeToString,
            ),
            'DeleteFromWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFromWaitlist,
                    request_deserializer=user__pb2.UID_ISBN.FromString,
                    response_serializer=user__pb2.SimpleMessage.SerializeToString,
            ),
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=user__pb2.UID.FromString,
                    response_serializer=user__pb2.FilteredBooksMessage.SerializeToString,
            ),
            'GetAllUsersInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsersInfo,
                    request_deserializer=user__pb2.EmptyInfo.FromString,
                    response_serializer=user__pb2.AllUsersInfoMessage.SerializeToString,
            ),
            'GetUserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInfo,
                    request_deserializer=user__pb2.UID.FromString,
                    response_serializer=user__pb2.UserInfoMessage.SerializeToString,
            ),
            'UpdateUserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserInfo,
                    request_deserializer=user__pb2.UpdateUserInfoRequest.FromString,
                    response_serializer=user__pb2.SimpleMessage.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user__pb2.UID.FromString,
                    response_serializer=user__pb2.SimpleMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.Users', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Users(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/GetBorrowedBooks',
            user__pb2.UID.SerializeToString,
            user__pb2.AllBooksMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/GetWaitlist',
            user__pb2.UID.SerializeToString,
            user__pb2.FilteredBooksMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendToWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/AppendToWaitlist',
            user__pb2.UID_ISBN.SerializeToString,
            user__pb2.SimpleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFromWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/DeleteFromWaitlist',
            user__pb2.UID_ISBN.SerializeToString,
            user__pb2.SimpleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/GetRecommendations',
            user__pb2.UID.SerializeToString,
            user__pb2.FilteredBooksMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllUsersInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/GetAllUsersInfo',
            user__pb2.EmptyInfo.SerializeToString,
            user__pb2.AllUsersInfoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/GetUserInfo',
            user__pb2.UID.SerializeToString,
            user__pb2.UserInfoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/UpdateUserInfo',
            user__pb2.UpdateUserInfoRequest.SerializeToString,
            user__pb2.SimpleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Users/DeleteUser',
            user__pb2.UID.SerializeToString,
            user__pb2.SimpleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
